[package]
name = "acrylic"
version = "0.1.7"
edition = "2021"
authors = [ "Nathan ROYER <nathan.royer.pro@gmail.com>" ]
description = "WIP UI toolkit"
license = "MIT"
keywords = ["toolkit", "gui", "ui", "xml"]
repository = "https://github.com/NathanRoyer/acrylic"
readme = "README.md"

[dependencies]
ab_glyph = { version = "0.2", optional = true }
bitflags = "1.3"

[features]
default = [ "text" ]
text = [ "ab_glyph" ]

[dev-dependencies]
png = "0.17"

[[example]]
name = "demo"
