[workspace]
members = [ "acrylic", "acrylic-web", "acrylic-wayland", "acrylic-png" ]
default-members = [ "acrylic", "acrylic-web", "acrylic-wayland", "acrylic-png" ]
resolver = "2"
readme = "README.md"
